spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contactsdb
    username: postgres
    password: kuldip
    driver-class-name: org.postgresql.Driver
  Jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true